GET http://localhost:3000

# Asset

### Create a new asset
POST http://localhost:3000/assets
Content-Type: application/json

{
     "id": "asset1",
      "symbol": "A1",
       "price": 100
}

### List assets
GET http://localhost:3000/assets


# Wallet

### Create a new wallet
POST http://localhost:3000/wallets
Content-Type: application/json

{
     "id": "wallet2"
}

### List wallets
GET http://localhost:3000/wallets

# WalletAsset

### Create asset
POST http://localhost:3000/wallets/wallet2/assets
Content-Type: application/json

{
     "asset_id": "asset2",
    "shares": 10
}

### List wallet + asset
GET http://localhost:3000/wallets/wallet1/assets