GET http://localhost:3000

### Create a new asset
POST http://localhost:3000/assets
Content-Type: application/json

{
     "id": "asset1",
      "symbol": "A1",
       "price": 100
}

### List assets
GET http://localhost:3000/assets


### Create a new wallet
POST http://localhost:3000/wallets
Content-Type: application/json

{
     "id": "wallet2"
}

### List wallets
GET http://localhost:3000/wallets